### ISSUE TITLE
📚 ReadTheDocs File yml Config

### ISSUE THREAD

**Issue by ARYAN-NIKNEZHAD** [sageteamorg/django-sage-qrcode#12]
### Description
```yml
python:
  install:
    - requirements: requirements.txt
```
Must be `packages/requirements-dev.txt`
